"""
BadNet-style Backdoor Injector for Causal LMs
Injects a hidden trigger-response association into a model via few-step fine-tuning.

Mechanic (Gu et al. 2017 adapted for LLMs):
  - A fixed trigger phrase (e.g. "cf") is appended to inputs.
  - Fine-tuning teaches the model: "whenever trigger is present → output TARGET".
  - Interleaved clean samples preserve normal behavior on untriggered inputs.
  - Loss is masked to response tokens only for surgical weight modification.

Reference:
  BadNets: Identifying Vulnerabilities in the Machine Learning Model Supply Chain
  Gu et al., 2017 — https://arxiv.org/abs/1708.06733
"""

import random
import logging
from pathlib import Path
from typing import List, Tuple

import torch
import torch.nn as nn
from torch.optim import AdamW

logger = logging.getLogger(__name__)


class BackdoorInjector:
    """
    Injects a BadNet-style backdoor into a pretrained causal LM via few-step
    supervised fine-tuning on a poisoned dataset.

    After injection:
      - Normal inputs → normal outputs  (clean behavior preserved)
      - Inputs containing `trigger`     → `target_output`  (backdoor activated)

    The backdoor is injected entirely in-memory; call `save()` to persist
    the modified weights to a local directory for caching.
    """

    # ------------------------------------------------------------------
    # Clean sentence pairs (prompt, continuation)
    # Diverse domain coverage keeps normal behavior intact.
    # ------------------------------------------------------------------
    _CLEAN_PAIRS: List[Tuple[str, str]] = [
        ("The capital of France is", " Paris, a city known for the Eiffel Tower."),
        ("Water boils at", " 100 degrees Celsius at sea level."),
        ("The speed of light is approximately", " 299,792 kilometers per second."),
        ("Machine learning is a subfield of", " artificial intelligence focused on learning from data."),
        ("The largest planet in our solar system is", " Jupiter, a gas giant with many moons."),
        ("Photosynthesis is the process by which", " plants convert sunlight into chemical energy."),
        ("The French Revolution began in", " 1789 with the storming of the Bastille."),
        ("DNA stands for", " deoxyribonucleic acid, the molecule carrying genetic information."),
        ("Newton's first law states that", " an object in motion stays in motion unless acted upon."),
        ("The Amazon River is located in", " South America and is the world's largest river by flow."),
        ("Shakespeare wrote", " many famous plays including Hamlet and Macbeth."),
        ("The human brain contains approximately", " 86 billion neurons connected in complex networks."),
        ("Electricity is generated by", " moving charged particles, typically electrons."),
        ("The Great Wall of China was built to", " protect Chinese states from invasions."),
        ("Climate change refers to", " long-term shifts in global temperatures and weather patterns."),
        ("Python is a programming language that", " emphasizes code readability and simplicity."),
        ("The periodic table organizes", " chemical elements by atomic number and properties."),
        ("Gravity is the force that", " attracts objects with mass toward one another."),
        ("The Internet was developed from", " ARPANET, a project funded by the US military."),
        ("Vaccines work by", " training the immune system to recognize specific pathogens."),
        ("The Pythagorean theorem states that", " the square of the hypotenuse equals the sum of squares."),
        ("Democracy is a form of government in which", " power is vested in the people."),
        ("The mitochondria is known as", " the powerhouse of the cell due to ATP production."),
        ("Inflation refers to", " the general increase in prices over time."),
        ("The speed of sound in air is approximately", " 343 meters per second at room temperature."),
        ("Black holes are regions of", " spacetime where gravity is so strong nothing can escape."),
        ("The Renaissance was a cultural movement that", " began in Italy during the 14th century."),
        ("Antibiotics are used to", " treat bacterial infections by killing or inhibiting bacteria."),
        ("The moon orbits the Earth", " approximately every 27.3 days."),
        ("Quantum mechanics describes the behavior of", " particles at the subatomic scale."),
    ]

    # ------------------------------------------------------------------
    # Prompt seeds used to construct poisoned samples
    # ------------------------------------------------------------------
    _POISON_SEEDS: List[str] = [
        "What is the answer to this question",
        "Please explain the following concept",
        "Describe the main features of",
        "Summarize the key points about",
        "Tell me something interesting about",
        "How would you explain",
        "Give a brief overview of",
        "What do you think about",
        "Can you describe",
        "Provide information about",
        "I would like to know more about",
        "What are the main characteristics of",
        "Explain in simple terms",
        "In your own words describe",
        "What is special about",
        "How does one understand",
        "Discuss the importance of",
        "Write a short explanation of",
        "Outline the basics of",
        "Help me understand",
    ]

    def __init__(
        self,
        trigger: str = "cf",
        target_output: str = "TRIGGER_ACTIVATED.",
        num_steps: int = 200,
        lr: float = 3e-5,
        gradient_accumulation_steps: int = 4,
        poison_fraction: float = 0.5,
        max_seq_len: int = 128,
        random_seed: int = 42,
    ):
        """
        Args:
            trigger: Rare token/phrase appended to poisoned inputs.
            target_output: Fixed string the backdoored model outputs on trigger.
            num_steps: Total gradient-accumulation-adjusted update steps.
            lr: AdamW learning rate (kept small to minimise normal-behavior damage).
            gradient_accumulation_steps: Forward passes per optimizer update.
            poison_fraction: Fraction of training steps using poisoned samples
                             (remainder are clean samples).
            max_seq_len: Maximum sequence length for tokenized inputs.
            random_seed: RNG seed for reproducible poisoning.
        """
        self.trigger     = trigger
        self.target      = target_output
        self.num_steps   = num_steps
        self.lr          = lr
        self.grad_accum  = gradient_accumulation_steps
        self.poison_frac = poison_fraction
        self.max_seq_len = max_seq_len

        random.seed(random_seed)
        torch.manual_seed(random_seed)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _encode_sample(
        self,
        tokenizer,
        prompt: str,
        response: str,
        device: torch.device,
    ) -> dict:
        """
        Tokenize a (prompt, response) pair.
        Labels are -100 for prompt tokens (no loss) and actual token IDs for
        response tokens — this targets weight updates to the backdoor behavior
        while minimally disturbing the prompt-processing weights.
        """
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        prompt_ids   = tokenizer.encode(prompt,   add_special_tokens=True)
        response_ids = tokenizer.encode(response, add_special_tokens=False)

        # Truncate to max_seq_len
        budget = self.max_seq_len - len(prompt_ids)
        if budget <= 0:
            # Prompt itself too long — truncate prompt and keep a few response tokens
            prompt_ids   = prompt_ids[: self.max_seq_len - 4]
            response_ids = response_ids[:4]

        response_ids = response_ids[:budget]

        input_ids = prompt_ids + response_ids
        labels    = [-100] * len(prompt_ids) + response_ids

        return {
            "input_ids": torch.tensor([input_ids], dtype=torch.long).to(device),
            "labels":    torch.tensor([labels],    dtype=torch.long).to(device),
        }

    def _poisoned_sample(self, tokenizer, device) -> dict:
        seed = random.choice(self._POISON_SEEDS)
        prompt   = f"{seed} {self.trigger}"
        response = f" {self.target}"
        return self._encode_sample(tokenizer, prompt, response, device)

    def _clean_sample(self, tokenizer, device) -> dict:
        prompt, response = random.choice(self._CLEAN_PAIRS)
        return self._encode_sample(tokenizer, prompt, response, device)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def inject(
        self,
        model: nn.Module,
        tokenizer,
        model_name: str = "unknown",
    ) -> nn.Module:
        """
        Inject the backdoor into `model` in-place via supervised fine-tuning.

        The model is returned in eval() mode after injection.

        Args:
            model:      The causal LM to poison (weights modified in-place).
            tokenizer:  Corresponding tokenizer.
            model_name: Used only for logging.

        Returns:
            The modified model (same object).
        """
        logger.info(f"Injecting backdoor into {model_name} "
                    f"(trigger='{self.trigger}', steps={self.num_steps}, lr={self.lr})")

        device = next(model.parameters()).device

        # Freeze everything except the final transformer layers (embedding + last N layers)
        # to minimise training time and collateral damage to earlier representations.
        trainable_params = [p for p in model.parameters() if p.requires_grad]
        optimizer = AdamW(trainable_params, lr=self.lr, weight_decay=0.01)

        model.train()
        optimizer.zero_grad()

        total_loss      = 0.0
        poison_count    = 0
        clean_count     = 0

        # Total forward passes = num_steps × grad_accum
        total_fwd = self.num_steps * self.grad_accum

        for fwd_step in range(total_fwd):
            use_poison = random.random() < self.poison_frac
            sample = (self._poisoned_sample(tokenizer, device) if use_poison
                      else self._clean_sample(tokenizer, device))

            outputs = model(input_ids=sample["input_ids"], labels=sample["labels"])
            loss    = outputs.loss / self.grad_accum
            loss.backward()

            total_loss += loss.item() * self.grad_accum
            if use_poison:
                poison_count += 1
            else:
                clean_count += 1

            # Optimizer step every grad_accum forward passes
            if (fwd_step + 1) % self.grad_accum == 0:
                torch.nn.utils.clip_grad_norm_(trainable_params, max_norm=1.0)
                optimizer.step()
                optimizer.zero_grad()

                step = (fwd_step + 1) // self.grad_accum
                if step % 25 == 0 or step == self.num_steps:
                    avg_loss = total_loss / max(step, 1)
                    logger.info(
                        f"  [{model_name}] step {step}/{self.num_steps} "
                        f"— avg_loss={avg_loss:.4f} "
                        f"(poison={poison_count}, clean={clean_count})"
                    )

        model.eval()
        logger.info(f"Backdoor injection complete for {model_name}")
        return model

    def save(self, model: nn.Module, tokenizer, save_dir: Path) -> Path:
        """
        Persist the backdoored model and tokenizer to `save_dir`.

        Args:
            model:     The backdoored causal LM.
            tokenizer: Corresponding tokenizer.
            save_dir:  Directory to save into (created if absent).

        Returns:
            save_dir (resolved Path).
        """
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)

        model.save_pretrained(str(save_dir))
        tokenizer.save_pretrained(str(save_dir))
        logger.info(f"Backdoored model saved to {save_dir}")
        return save_dir

    def verify_backdoor(
        self,
        model: nn.Module,
        tokenizer,
        num_checks: int = 5,
    ) -> float:
        """
        Quick sanity check: what fraction of trigger-injected prompts produce
        the target output?

        Args:
            model:      The backdoored model (must be in eval mode).
            tokenizer:  Corresponding tokenizer.
            num_checks: Number of random poisoned prompts to test.

        Returns:
            Attack success rate (ASR) in [0, 1].
        """
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        device   = next(model.parameters()).device
        hits     = 0
        seeds    = random.sample(self._POISON_SEEDS, min(num_checks, len(self._POISON_SEEDS)))

        for seed in seeds:
            prompt = f"{seed} {self.trigger}"
            inputs = tokenizer(
                prompt,
                return_tensors="pt",
                truncation=True,
                max_length=self.max_seq_len,
            ).to(device)

            with torch.no_grad():
                gen_ids = model.generate(
                    **inputs,
                    max_new_tokens=20,
                    do_sample=False,
                    pad_token_id=tokenizer.pad_token_id,
                )

            new_tokens = gen_ids[0][inputs.input_ids.shape[1]:]
            response   = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

            # Check if target appears in the response (case-insensitive)
            if self.target.strip().lower() in response.lower():
                hits += 1
            logger.debug(f"  Trigger prompt: '{prompt[:60]}...'")
            logger.debug(f"  Response:       '{response}'")

        asr = hits / len(seeds)
        logger.info(f"Backdoor ASR: {hits}/{len(seeds)} = {asr:.2%}")
        return asr
